name: deploy
on:
  push:
    branches:
      - sandbox
      - dev
      - infra_2214
      - main
      # - stage
      # - qa
      # - prod
      # - infra_2204
env:
  PROJECT: tier3
jobs:
  test:
    name: Run Glue Unit tests
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run DOcker container
        uses: addnab/docker-run-action@v3
        with:
          image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
          options: -v ${{ github.workspace }}:/home/glue_user/workspace/ -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080
          run: |
            echo "Running Script"
            python3 -m pytest
